title: Cloud Otter
description: What a cloud architect is thinking.
show_downloads: true
google_analytics:
theme: Cloud Otter
remote_theme: pages-themes/architect@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one